"""Add code verify to users table

Revision ID: 052a2beca721
Revises: 04d2dc446735
Create Date: 2025-11-19 19:46:37.247452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052a2beca721'
down_revision: Union[str, None] = '04d2dc446735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('reset_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_code_expires_at')
    op.drop_column('users', 'reset_code')
    # ### end Alembic commands ###
