"""Add video_platform to lecture_content

Revision ID: 1b677128e5a3
Revises: 4d06a81abf59
Create Date: 2025-11-15 22:42:40.807419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b677128e5a3'
down_revision: Union[str, None] = '4d06a81abf59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_contents', sa.Column('video_platform', sa.String(length=50), server_default='youtube', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_contents', 'video_platform')
    # ### end Alembic commands ###
