"""Add new login method

Revision ID: 3981cbcc4631
Revises: f1234567890b
Create Date: 2025-11-26 16:34:42.707874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3981cbcc4631'
down_revision: Union[str, None] = 'f1234567890b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_generated_questions', 'topic',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('user_generated_questions', 'question_category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               comment='Primary question category: standard, critical, linking',
               existing_nullable=True)
    op.alter_column('user_generated_questions', 'cognitive_level',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               comment='Primary cognitive level: remember, understand, apply, analyze, evaluate, create',
               existing_nullable=True)
    op.add_column('users', sa.Column('academic_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_academic_id'), 'users', ['academic_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_academic_id'), table_name='users')
    op.drop_column('users', 'academic_id')
    op.alter_column('user_generated_questions', 'cognitive_level',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Primary cognitive level: remember, understand, apply, analyze, evaluate, create',
               existing_nullable=True)
    op.alter_column('user_generated_questions', 'question_category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Primary question category: standard, critical, linking',
               existing_nullable=True)
    op.alter_column('user_generated_questions', 'topic',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
