"""Edit course table

Revision ID: 4d06a81abf59
Revises: ea6615ff95c5
Create Date: 2025-11-15 21:52:05.512035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d06a81abf59'
down_revision: Union[str, None] = 'ea6615ff95c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_free', sa.Boolean(), nullable=False))
    op.add_column('lecture_contents', sa.Column('quiz_duration', sa.Integer(), nullable=True))
    op.add_column('lecture_contents', sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.add_column('lecture_contents', sa.Column('passing_score', sa.Integer(), nullable=True))
    op.add_column('lecture_contents', sa.Column('show_correct_answers', sa.Integer(), nullable=False))
    op.add_column('lecture_contents', sa.Column('randomize_questions', sa.Integer(), nullable=False))
    op.add_column('lecture_contents', sa.Column('randomize_options', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_contents', 'randomize_options')
    op.drop_column('lecture_contents', 'randomize_questions')
    op.drop_column('lecture_contents', 'show_correct_answers')
    op.drop_column('lecture_contents', 'passing_score')
    op.drop_column('lecture_contents', 'max_attempts')
    op.drop_column('lecture_contents', 'quiz_duration')
    op.drop_column('courses', 'is_free')
    # ### end Alembic commands ###
