"""edit_chat_session_tables

Revision ID: 6a5ee09a0a94
Revises: 43a2ccc3e785
Create Date: 2025-12-18 15:13:49.671131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5ee09a0a94'
down_revision: Union[str, None] = '43a2ccc3e785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('session_type', sa.String(length=20), nullable=False, server_default='asking'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'session_type')
    # ### end Alembic commands ###
