"""Add tg_id to admin table

Revision ID: 6eda97437624
Revises: d008e789d0c7
Create Date: 2025-11-16 23:20:56.343000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eda97437624'
down_revision: Union[str, None] = 'd008e789d0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('telegram_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'admins', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'telegram_id')
    # ### end Alembic commands ###
