"""edit_chat_session_tables

Revision ID: 8d5cc7c004b0
Revises: 6a5ee09a0a94
Create Date: 2025-12-18 20:52:15.374274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5cc7c004b0'
down_revision: Union[str, None] = '6a5ee09a0a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
