"""Add post moderation and reporting system

Revision ID: 976350cba7e2
Revises: ed41b1e03f45
Create Date: 2025-11-14 22:22:41.446061

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "976350cba7e2"
down_revision: Union[str, None] = "ed41b1e03f45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "post_status",
            sa.String(length=20),
            nullable=False,
            server_default="accepted",
        ),
    )
    op.create_index(
        op.f("ix_posts_post_status"), "posts", ["post_status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_post_status"), table_name="posts")
    op.drop_column("posts", "post_status")
    # ### end Alembic commands ###
