"""Add community auto accept posts

Revision ID: 9dbe6b06f7b6
Revises: 976350cba7e2
Create Date: 2025-11-14 23:40:49.437034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dbe6b06f7b6'
down_revision: Union[str, None] = '976350cba7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('auto_accept_posts', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'auto_accept_posts')
    # ### end Alembic commands ###
