"""Add new thing in ugq

Revision ID: dac520301aa6
Revises: d9dd6e0072a9
Create Date: 2025-11-23 01:50:39.578391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac520301aa6'
down_revision: Union[str, None] = 'd9dd6e0072a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_generated_questions', sa.Column('question_category', sa.String(length=100), nullable=True))
    op.add_column('user_generated_questions', sa.Column('cognitive_level', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_generated_questions', 'cognitive_level')
    op.drop_column('user_generated_questions', 'question_category')
    # ### end Alembic commands ###
