"""Add video_platform and resumable quiz attempts support

Revision ID: df60cb254816
Revises: 1b677128e5a3
Create Date: 2025-11-15 22:50:38.135292

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "df60cb254816"
down_revision: Union[str, None] = "1b677128e5a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz_attempts",
        sa.Column("is_completed", sa.Integer(), nullable=False, server_default="1"),
    )
    op.alter_column(
        "quiz_attempts",
        "answers",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "quiz_attempts",
        "score",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=True,
    )
    op.alter_column(
        "quiz_attempts", "correct_answers", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "quiz_attempts", "time_taken", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "quiz_attempts",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quiz_attempts",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "quiz_attempts", "time_taken", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "quiz_attempts", "correct_answers", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "quiz_attempts",
        "score",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=False,
    )
    op.alter_column(
        "quiz_attempts",
        "answers",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.drop_column("quiz_attempts", "is_completed")
    # ### end Alembic commands ###
