"""Edit course table

Revision ID: ea6615ff95c5
Revises: 9dbe6b06f7b6
Create Date: 2025-11-15 21:20:48.099080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea6615ff95c5'
down_revision: Union[str, None] = '9dbe6b06f7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'subject_id')
    op.drop_column('courses', 'is_to_send_parent_follow_up_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_to_send_parent_follow_up_message', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
