"""Add admin_id to community_members

Revision ID: ed41b1e03f45
Revises: 
Create Date: 2025-11-14 19:30:56.709610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed41b1e03f45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.add_column('community_members', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.alter_column('community_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('unique_community_member', 'community_members', type_='unique')
    op.create_index(op.f('ix_community_members_admin_id'), 'community_members', ['admin_id'], unique=False)
    op.create_unique_constraint('unique_community_admin_member', 'community_members', ['community_id', 'admin_id'])
    op.create_unique_constraint('unique_community_user_member', 'community_members', ['community_id', 'user_id'])
    op.create_foreign_key(None, 'community_members', 'admins', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'community_members', type_='foreignkey')
    op.drop_constraint('unique_community_user_member', 'community_members', type_='unique')
    op.drop_constraint('unique_community_admin_member', 'community_members', type_='unique')
    op.drop_index(op.f('ix_community_members_admin_id'), table_name='community_members')
    op.create_unique_constraint('unique_community_member', 'community_members', ['community_id', 'user_id'])
    op.alter_column('community_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('community_members', 'admin_id')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    # ### end Alembic commands ###
