# app/models/user_generated_question.py
from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.core.database import Base


class UserGeneratedQuestion(Base):
    """
    Questions generated by users using AI.
    Can be shared publicly or kept private.
    """

    __tablename__ = "user_generated_questions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    topic = Column(Text, nullable=False)

    # Question settings
    difficulty = Column(
        String(20), nullable=False, default="medium"
    )  # easy, medium, hard
    question_type = Column(
        String(50), nullable=False, default="multiple_choice"
    )  # multiple_choice, true_false, essay, mixed

    # Privacy and sharing
    is_public = Column(
        Boolean, default=False, nullable=False
    )  # Public questions can be attempted by anyone

    # Questions stored as JSONB array
    questions = Column(JSONB, nullable=False, default=[])
    total_questions = Column(Integer, nullable=False, default=0)

    # Question categorization (aggregated from questions)
    question_category = Column(
        String(50),
        nullable=True,
        comment="Primary question category: standard, critical, linking",
    )
    cognitive_level = Column(
        String(50),
        nullable=True,
        comment="Primary cognitive level: remember, understand, apply, analyze, evaluate, create",
    )

    # Source information
    source_type = Column(String(20), nullable=False)  # 'topic' or 'pdf'
    source_file_name = Column(String(255), nullable=True)  # PDF filename if from PDF

    # Statistics
    attempt_count = Column(
        Integer, nullable=False, default=0
    )  # How many times attempted by others
    # Timestamps
    created_at = Column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # Relationships
    user = relationship("User", backref="generated_questions")
    attempts = relationship(
        "UserGeneratedQuestionAttempt",
        back_populates="question_set",
        cascade="all, delete-orphan",
    )

    class Config:
        from_attributes = True


class UserGeneratedQuestionAttempt(Base):
    """
    Track attempts on user-generated questions
    """

    __tablename__ = "user_generated_question_attempts"

    id = Column(Integer, primary_key=True, index=True)
    question_set_id = Column(
        Integer, ForeignKey("user_generated_questions.id"), nullable=False, index=True
    )
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)

    # Attempt results
    answers = Column(
        JSONB, nullable=True, default=[]
    )  # User's answers with correctness
    score = Column(Integer, nullable=True)  # Percentage score
    correct_answers = Column(Integer, nullable=True)
    total_questions = Column(Integer, nullable=False)
    time_taken = Column(Integer, nullable=True)  # Seconds

    # Status
    is_completed = Column(Boolean, default=False, nullable=False)

    # Timestamps
    started_at = Column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    completed_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    question_set = relationship("UserGeneratedQuestion", back_populates="attempts")
    user = relationship("User", backref="question_attempts")

    class Config:
        from_attributes = True


class GuestQuestionAttempt(Base):
    """
    Track guest attempts on user-generated questions (users without accounts)
    """

    __tablename__ = "guest_question_attempts"

    id = Column(Integer, primary_key=True, index=True)
    question_set_id = Column(
        Integer, ForeignKey("user_generated_questions.id"), nullable=False, index=True
    )
    phone_number = Column(String(20), nullable=False, index=True)

    # Guest info (optional, for future reference)
    guest_name = Column(String(100), nullable=True)

    # Attempt results
    answers = Column(
        JSONB, nullable=True, default=[]
    )  # Guest's answers with correctness
    score = Column(Integer, nullable=True)  # Percentage score
    correct_answers = Column(Integer, nullable=True)
    total_questions = Column(Integer, nullable=False)
    time_taken = Column(Integer, nullable=True)  # Seconds

    # Status
    is_completed = Column(Boolean, default=False, nullable=False)

    # Timestamps
    started_at = Column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    completed_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    question_set = relationship("UserGeneratedQuestion", backref="guest_attempts")

    class Config:
        from_attributes = True
